### ISSUE TITLE
ArrayIndexOutOfBoundsException observed when running `racePair` benchmark

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#1045]
```
Exception in thread "io-compute-4" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
[error]         at cats.effect.ArrayStack.pop(ArrayStack.scala:35)
[error]         at cats.effect.IOFiber.loop$1(IOFiber.scala:358)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1(IOFiber.scala:372)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1$adapted(IOFiber.scala:337)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5(IOFiber.scala:503)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5$adapted(IOFiber.scala:503)
[error]         at cats.effect.CallbackStack.apply(CallbackStack.scala:45)
[error]         at cats.effect.IOFiber.done(IOFiber.scala:195)
[error]         at cats.effect.IOFiber.runTerminusSuccessK(IOFiber.scala:820)
[error]         at cats.effect.IOFiber.succeeded(IOFiber.scala:596)
[error]         at cats.effect.IOFiber.runLoop(IOFiber.scala:303)
[error]         at cats.effect.IOFiber.execR(IOFiber.scala:699)
[error]         at cats.effect.IOFiber.run(IOFiber.scala:679)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by vasilmkd** [comment]
Again:
```
[info] # JMH version: 1.21
[info] # VM version: JDK 14.0.1, OpenJDK 64-Bit Server VM, 14.0.1+7-Ubuntu-1ubuntu1
[info] # VM invoker: /usr/lib/jvm/java-14-openjdk-amd64/bin/java
[info] # VM options: <none>
[info] # Warmup: 10 iterations, 10 s each
[info] # Measurement: 10 iterations, 10 s each
[info] # Timeout: 10 min per iteration
[info] # Threads: 1 thread, will synchronize iterations
[info] # Benchmark mode: Throughput, ops/time
[info] # Benchmark: cats.effect.benchmarks.AsyncBenchmark.racePair
[info] # Parameters: (size = 100)
[info] # Run progress: 17.39% complete, ETA 02:06:53
[info] # Fork: 1 of 2
[error] Exception in thread "io-compute-1" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
[error]         at cats.effect.ArrayStack.pop(ArrayStack.scala:35)
[error]         at cats.effect.IOFiber.loop$1(IOFiber.scala:358)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1(IOFiber.scala:372)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1$adapted(IOFiber.scala:337)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5(IOFiber.scala:503)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5$adapted(IOFiber.scala:503)
[error]         at cats.effect.CallbackStack.apply(CallbackStack.scala:45)
[error]         at cats.effect.IOFiber.done(IOFiber.scala:195)
[error]         at cats.effect.IOFiber.runTerminusSuccessK(IOFiber.scala:820)
[error]         at cats.effect.IOFiber.succeeded(IOFiber.scala:596)
[error]         at cats.effect.IOFiber.runLoop(IOFiber.scala:303)
[error]         at cats.effect.IOFiber.execR(IOFiber.scala:699)
[error]         at cats.effect.IOFiber.run(IOFiber.scala:679)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:832)
[error] Exception in thread "io-compute-2" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
[error]         at cats.effect.ArrayStack.pop(ArrayStack.scala:35)
[error]         at cats.effect.IOFiber.loop$1(IOFiber.scala:358)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1(IOFiber.scala:372)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1$adapted(IOFiber.scala:337)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5(IOFiber.scala:503)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5$adapted(IOFiber.scala:503)
[error]         at cats.effect.CallbackStack.apply(CallbackStack.scala:45)
[error]         at cats.effect.IOFiber.done(IOFiber.scala:195)
[error]         at cats.effect.IOFiber.runTerminusSuccessK(IOFiber.scala:820)
[error]         at cats.effect.IOFiber.succeeded(IOFiber.scala:596)
[error]         at cats.effect.IOFiber.runLoop(IOFiber.scala:303)
[error]         at cats.effect.IOFiber.execR(IOFiber.scala:699)
[error]         at cats.effect.IOFiber.run(IOFiber.scala:679)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:832)
[error] Exception in thread "io-compute-5" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
[error]         at cats.effect.ArrayStack.pop(ArrayStack.scala:35)
[error]         at cats.effect.IOFiber.loop$1(IOFiber.scala:358)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1(IOFiber.scala:372)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1$adapted(IOFiber.scala:337)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5(IOFiber.scala:503)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5$adapted(IOFiber.scala:503)
[error]         at cats.effect.CallbackStack.apply(CallbackStack.scala:45)
[error]         at cats.effect.IOFiber.done(IOFiber.scala:195)
[error]         at cats.effect.IOFiber.runTerminusSuccessK(IOFiber.scala:820)
[error]         at cats.effect.IOFiber.succeeded(IOFiber.scala:596)
[error]         at cats.effect.IOFiber.runLoop(IOFiber.scala:303)
[error]         at cats.effect.IOFiber.execR(IOFiber.scala:699)
[error]         at cats.effect.IOFiber.run(IOFiber.scala:679)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:832)
[error] Exception in thread "io-compute-6" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
[error]         at cats.effect.ArrayStack.pop(ArrayStack.scala:35)
[error]         at cats.effect.IOFiber.loop$1(IOFiber.scala:358)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1(IOFiber.scala:372)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$1$adapted(IOFiber.scala:337)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5(IOFiber.scala:503)
[error]         at cats.effect.IOFiber.$anonfun$runLoop$5$adapted(IOFiber.scala:503)
[error]         at cats.effect.CallbackStack.apply(CallbackStack.scala:45)
[error]         at cats.effect.IOFiber.done(IOFiber.scala:195)
[error]         at cats.effect.IOFiber.runTerminusSuccessK(IOFiber.scala:820)
[error]         at cats.effect.IOFiber.succeeded(IOFiber.scala:596)
[error]         at cats.effect.IOFiber.runLoop(IOFiber.scala:303)
[error]         at cats.effect.IOFiber.execR(IOFiber.scala:699)
[error]         at cats.effect.IOFiber.run(IOFiber.scala:679)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by djspiewak** [comment]
Minimized reproduction:

```scala
    "ensure async callback is suppressed during suspension of finalizers" in ticked { implicit ticker =>
      var cb: Either[Throwable, Unit] => Unit = null

      val subject = IO.async[Unit] { cb0 =>
        IO {
          cb = cb0

          Some(IO.never)
        }
      }

      val test = for {
        f <- subject.start
        _ <- IO(ticker.ctx.tickAll())   // schedule everything
        _ <- f.cancel.start
        _ <- IO(ticker.ctx.tickAll())   // get inside the finalizer suspension
        _ <- IO(cb(Right(())))
        _ <- IO(ticker.ctx.tickAll())   // show that the finalizer didn't explode
      } yield ()

      test must nonTerminate    // ...but not throw an exception
    }
```

In words:

1. Fiber hits an `Async` with a finalizer and suspends
2. Fiber is canceled before callback completes
3. `asyncCancel` get the runloop
4. All the things are masked and the first finalizer is popped
5. Finalizer *itself* contains an `Async`… which suspends
6. The callback from the first `Async` completes *during* this suspension
7. It gets the runloop(!!!!) and the first thing it tries to do is pop its own finalizer
8. Fortunately that was the only finalizer… but it's already been popped! Hijinx ensue
