### ISSUE TITLE
Benchmarks failing on series/2.x

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1106]
I tried to run the benchmarks on two different computers, and I'm getting the following error:
```
[IJ]sbt:root> benchmarksNext/jmh:run -wi 5 -i 5 -f 1 -t 1 cats.effect.benchmarks.DeepBindBenchmark
[info] Compiling 79 Scala sources and 2 Java sources to /Users/rahsan/Desktop/oss/cats-effect/core/jvm/target/scala-2.13/classes ...
[info] Done compiling.
[info] running (fork) org.openjdk.jmh.Main -wi 5 -i 5 -f 1 -t 1 cats.effect.benchmarks.DeepBindBenchmark
[error] Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
[error] 	at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:98)
[error] 	at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:122)
[error] 	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:263)
[error] 	at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
[error] 	at org.openjdk.jmh.Main.main(Main.java:71)
[error] Nonzero exit code returned from runner: 1
[error] (benchmarksNext / Jmh / run) Nonzero exit code returned from runner: 1
[error] Total time: 61 s (01:01), completed Aug 19, 2020 5:57:45 PM
[IJ]sbt:root> 
```

**Comment by vasilmkd** [comment]
Possibly happened in #1095 too?

**Comment by keynmol** [comment]
I did a bit of git bisecting and I think like [this commit](https://github.com/typelevel/cats-effect/commit/de3e3fcf8099e6ff3ed24196a5f30142c6c24a29) introduced some general problem with running benchmarks

```scala
de3e3fcf8099e6ff3ed24196a5f30142c6c24a29 is the first bad commit
commit de3e3fcf8099e6ff3ed24196a5f30142c6c24a29
Author: Daniel Spiewak <djspiewak@gmail.com>
Date:   Sat Aug 15 18:57:22 2020 -0600

    Ported the build over to sbt-spiewak
```
