### ISSUE TITLE
Work stealing thread pool not parking

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1327]
I was running a test application today in SBT where it doesn't fork the JVM. I noticed that after the application terminated, the SBT process was seeing 800% CPU utilization. I captured a thread dump and saw:
```
"io-compute-1" #197 daemon prio=5 os_prio=31 tid=0x00007feae741b800 nid=0x13d03 runnable [0x000070000fef4000]
   java.lang.Thread.State: RUNNABLE
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c7322960> (a cats.effect.unsafe.WorkStealingThreadPool)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at cats.effect.unsafe.WorkerThread.park(WorkerThread.scala:166)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:268)

   Locked ownable synchronizers:
        - None
```
It seems like threads these threads are actually executing and _not_ parking, which is causing the high CPU. Compare with a regular executor:
```

"pool-17-thread-12" #188 prio=5 os_prio=31 tid=0x00007f9e72278000 nid=0xb803 waiting on condition [0x0000700010aa5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c6c59170> (a java.util.concurrent.SynchronousQueue$TransferStack)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by vasilmkd** [comment]
Yeah, I'm not super confident in the `shutdown` procedure, we should review it in depth.

**Comment by vasilmkd** [comment]
It's weird how the thread says parking to wait for the pool, which is just a blocker object for monitoring purposes, it does not really matter what is there, but the thread is still in a Runnable state. 🤔

**Comment by vasilmkd** [comment]
I'm seeing the following: `Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"`
https://stackoverflow.com/questions/21464673/sbt-trapexitsecurityexception-thrown-at-sbt-run

This also happens if I switch to a fixed thread pool, but sbt doesn't continue in this case...

**Comment by djspiewak** [comment]
TrapExitSecurityException is sbt magic. We need to catch that and shut down the pool. It's basically a system exit which was suppressed.

**Comment by vasilmkd** [comment]
But it's really weird, the runloop of the worker threads is completely fine. It's just that they fail to `park()` after that and spin doing nothing. It's like the call to `park()` is somehow malformed after that exception.

**Comment by djspiewak** [comment]
I think the threads are interrupted, which would cause all subsequent parks to bail out immediately. Though, I would expect them to reraise the interrupt, so that's weird.

**Comment by vasilmkd** [comment]
@djspiewak You're right about the interruption. I was able to confirm this. Thanks, this gives me an idea.
