### ISSUE TITLE
MBean exception during shutdown of example

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2574]
```
[error] Exception in thread "io-cancel-hook" javax.management.InstanceNotFoundException: cats.effect.unsafe.metrics:type=LiveFiberSnapshotTrigger-7a765367
[error]     at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
[error]     at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427)
[error]     at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415)
[error]     at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546)
[error]     at cats.effect.unsafe.IORuntimeCompanionPlatform.$anonfun$registerFiberMonitorMBean$1(IORuntimeCompanionPlatform.scala:189)
[error]     at cats.effect.IOApp.$anonfun$main$3(IOApp.scala:225)
[error]     at cats.effect.IOApp.handleShutdown$1(IOApp.scala:299)
[error]     at cats.effect.IOApp.$anonfun$main$15(IOApp.scala:302)
[error]     at java.lang.Thread.run(Thread.java:748)
```

Discovered this when running the `LiveFiberSnapshot` example with `; set Test / run / fork := true; Test / run` in the **testsJVM** project.

**Comment by vasilmkd** [comment]
Hell yes. Any idea what to do here?
