### ISSUE TITLE
`IO` swallows fatal errors on JS

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2927]
First reported in https://github.com/disneystreaming/weaver-test/issues/503.

```scala
//> using scala "3.1.1"
//> using platform "scala-js"
//> using jsVersion "1.9.0"
//> using lib "org.typelevel::cats-effect::3.3.9"

import cats.effect._
import cats.effect.unsafe.implicits._

object Main {
  def main(args: Array[String]): Unit = {
    val io = IO(throw new VirtualMachineError {}).attempt.flatMap(IO.println) <* IO.println("BOOM")
    io.unsafeToFuture()
  }
}
```

```
Right(null)
BOOM
/tmp/main12791209756503579234.js:11013
    throw $ct_jl_IllegalStateException__T__(new $c_jl_IllegalStateException(), "Promise already completed.")
    ^

<ref *1> java.lang.IllegalStateException: Promise already completed.
    at $f_s_concurrent_Promise__complete__s_util_Try__s_concurrent_Promise (/tmp/main12791209756503579234.js:11013:45)
    at $c_s_concurrent_impl_Promise$DefaultPromise.complete__s_util_Try__s_concurrent_Promise (/tmp/main12791209756503579234.js:39414:10)
    at $f_s_concurrent_Promise__success__O__s_concurrent_Promise (/tmp/main12791209756503579234.js:11017:16)
    at $c_s_concurrent_impl_Promise$DefaultPromise.success__O__s_concurrent_Promise (/tmp/main12791209756503579234.js:39417:10)
    at $ps_Lcats_effect_IO__$anonfun$12__s_concurrent_Promise__O__V (/tmp/main12791209756503579234.js:13760:7)
    at $ps_Lcats_effect_IO__$anonfun$adapted$3__s_concurrent_Promise__O__O (/tmp/main12791209756503579234.js:13763:3)
    at /tmp/main12791209756503579234.js:13844:432
    at $c_sjsr_AnonFunction1.apply__O__O (/tmp/main12791209756503579234.js:23475:43)
    at $ps_Lcats_effect_IO__$anonfun$17$$anonfun$3__F1__F1__Lcats_effect_unsafe_IORuntime__Lcats_effect_IO__V (/tmp/main12791209756503579234.js:13784:13)
    at $ps_Lcats_effect_IO__$anonfun$18$$anonfun$adapted$3__F1__F1__Lcats_effect_unsafe_IORuntime__Lcats_effect_IO__O (/tmp/main12791209756503579234.js:13787:3) {
  jl_Throwable__f_s: 'Promise already completed.',
  jl_Throwable__f_e: null,
  jl_Throwable__f_enableSuppression: true,
  jl_Throwable__f_writableStackTrace: true,
  jl_Throwable__f_stackTraceStateInternal: [Circular *1],
  jl_Throwable__f_stackTrace: null,
  jl_Throwable__f_suppressed: null
}
```

Interestingly, this _doesn't_ happen when using `IOApp`.

```scala
object Main extends IOApp.Simple {
  def run = IO(throw new VirtualMachineError {}).attempt.flatMap(IO.println) <* IO.println("BOOM")
}
```

```
Main$$anon$1
  at Main$.run$$anonfun$1(/tmp/main650896950790062058.js:19523:9)
  at {anonymous}()(/tmp/main650896950790062058.js:19562:5)
  at scala.scalajs.runtime.AnonFunction0.apply(/tmp/main650896950790062058.js:24034:43)
  at cats.effect.IOFiber.runLoop(/tmp/main650896950790062058.js:36329:52)
  at cats.effect.IOFiber.execR(/tmp/main650896950790062058.js:37150:5)
  at cats.effect.IOFiber.run(/tmp/main650896950790062058.js:37592:7)
  at cats.effect.unsafe.FiberAwareExecutionContext.cats$effect$unsafe$FiberAwareExecutionContext$$_$execute$$anonfun$1(/tmp/main650896950790062058.js:14367:7)
  at cats.effect.unsafe.FiberAwareExecutionContext$$anon$1.run(/tmp/main650896950790062058.js:14405:73)
  at org.scalajs.macrotaskexecutor.MacrotaskExecutor$.execute$$anonfun$1(/tmp/main650896950790062058.js:26909:14)
  at org.scalajs.macrotaskexecutor.MacrotaskExecutor$.execute$$anonfun$adapted$1(/tmp/main650896950790062058.js:26912:3)
```

**Comment by armanbilge** [comment]
Woah. If I change the `unsafeToFuture` to `unsafeRunAndForget` then I get this:

```
Right(null)
BOOM
```

It's completely swallowed 🤯

**Comment by armanbilge** [comment]
Further minimized: replace `IO.delay` with `Async[IO].catchNonFatal` and it throws. `IO.delay` and `Async[IO].delay` swallow.

**Comment by armanbilge** [comment]
... and turns out it's nothing to do with JS. On JVM the error seems to be swallowed as well, except we don't get the subsequent `println`s like on JS.

**Comment by armanbilge** [comment]
Actually. Is this a problem in the executors? Like this part:

https://github.com/typelevel/cats-effect/blob/4d8e933c64aec4cd42d3d7b9ab043705b638a0a9/core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala#L500-L502

https://github.com/typelevel/cats-effect/blob/7eed52984ac674d5a50e32bf880b33202847dd46/core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala#L34-L35

**Comment by armanbilge** [comment]
> replace `IO.delay` with `Async[IO].catchNonFatal` and it throws.

I was confused about this, since these are not equivalent. A correct replacement is `IO(Async[IO].catchNonFatal(...)).flatten` which does swallow.

So, not sure about JVM. But definitely something weird going on in JS.

**Comment by djspiewak** [comment]
I think this might be related to the changes we made to adjust the WSTP to be more generic. The logic related to catching and transporting fatal errors shouldn't trigger on other runtimes, but it appears that's exactly what is happening

**Comment by armanbilge** [comment]
Hmm. I thought I'd checked, but I checked again now. At least the JS problem appears to be a regression introduced in 3.2.0.

**Comment by armanbilge** [comment]
Ok, bisected down to 468af80708b7753f5cb2eac3a61f15954f0b19db. Ping @vasilmkd 😇

**Comment by djspiewak** [comment]
This is being caused by `onFatalFailure` assuming that `Thread#interrupt()` works on all platforms. It doesn't work on Scala.js, so `onFatalFailure` ends up *returning* `null`, which is then treated as a result in this case. That's where the `null` in `Right(null)` is coming from.

We probably need to rethrow here rather than relying on interruption unless our `interrupted` flag had been set to `true`, but I'm not entirely clear on how those semantics would interact with our error relocation logic.

**Comment by armanbilge** [comment]
Related Scala.js PR:
- https://github.com/scala-js/scala-js/pull/1910

**Comment by djspiewak** [comment]
I wasn't able to reproduce this. :-(

```scala
  object FatalErrorRaw extends RawApp {
    def main(args: Array[String]): Unit = {
      import cats.effect.unsafe.implicits._
      val action = IO(throw new OutOfMemoryError("Boom!")).attempt.flatMap(_ => IO.println("sadness"))
      action.unsafeToFuture()
    }
  }
```

Did this with the following test:

```scala
        "exit on fatal error without IOApp" in {
          val h = platform(FatalErrorRaw, List.empty)
          h.stderr() must contain("Boom!")
          h.stdout() must not(contain("sadness"))
        }
```

The first assertion fails, but I think that's spurious. Commenting it out, the second assertion *passes*, meaning that the `sadness` println isn't being hit.

**Comment by armanbilge** [comment]
Huh.

```scala
//> using scala "3.1.1"
//> using platform "scala-js"
//> using jsVersion "1.9.0"
//> using lib "org.typelevel::cats-effect::3.3.9"

import cats.effect._
import cats.effect.unsafe.implicits._

object Main {
  def main(args: Array[String]): Unit = {
    val action = IO(throw new OutOfMemoryError("Boom!")).attempt.flatMap(_ => IO.println("sadness"))
    action.unsafeToFuture()
  }
}
```

```
$ node ./i2927.js
sadness
/workspace/sandbox/i2927.js:11013
    throw $ct_jl_IllegalStateException__T__(new $c_jl_IllegalStateException(), "Promise already completed.")
    ^

<ref *1> java.lang.IllegalStateException: Promise already completed.
    at $f_s_concurrent_Promise__complete__s_util_Try__s_concurrent_Promise (/workspace/sandbox/i2927.js:11013:45)
    at $c_s_concurrent_impl_Promise$DefaultPromise.complete__s_util_Try__s_concurrent_Promise (/workspace/sandbox/i2927.js:39392:10)
    at $f_s_concurrent_Promise__success__O__s_concurrent_Promise (/workspace/sandbox/i2927.js:11017:16)
    at $c_s_concurrent_impl_Promise$DefaultPromise.success__O__s_concurrent_Promise (/workspace/sandbox/i2927.js:39395:10)
    at $ps_Lcats_effect_IO__$anonfun$12__s_concurrent_Promise__O__V (/workspace/sandbox/i2927.js:13754:7)
    at $ps_Lcats_effect_IO__$anonfun$adapted$3__s_concurrent_Promise__O__O (/workspace/sandbox/i2927.js:13757:3)
    at /workspace/sandbox/i2927.js:13829:432
    at $c_sjsr_AnonFunction1.apply__O__O (/workspace/sandbox/i2927.js:23460:43)
    at $ps_Lcats_effect_IO__$anonfun$17$$anonfun$3__F1__F1__Lcats_effect_unsafe_IORuntime__Lcats_effect_IO__V (/workspace/sandbox/i2927.js:13778:13)
    at $ps_Lcats_effect_IO__$anonfun$18$$anonfun$adapted$3__F1__F1__Lcats_effect_unsafe_IORuntime__Lcats_effect_IO__O (/workspace/sandbox/i2927.js:13781:3) {
  jl_Throwable__f_s: 'Promise already completed.',
  jl_Throwable__f_e: null,
  jl_Throwable__f_enableSuppression: true,
  jl_Throwable__f_writableStackTrace: true,
  jl_Throwable__f_stackTraceStateInternal: [Circular *1],
  jl_Throwable__f_stackTrace: null,
  jl_Throwable__f_suppressed: null
}
```

I uploaded the JS if you want to see for yourself. `scala-cli package i2927.scala` to generate it.

https://gist.githubusercontent.com/armanbilge/bd1a9d1c196f47fa7d6f7764906a3749/raw/9423b9112555ddf7265c49e9552e90050cad01f3/i2927.js

**Comment by djspiewak** [comment]
@armanbilge Would you mind taking a look at my `bug/fatal-error-continuation` branch (on my fork)? I'm trying to get it baked into an automated test and I'm not sure if I've messed up the harness somehow.

**Comment by armanbilge** [comment]
@djspiewak you are missing an `h.awaitStatus` in the spec, like the one above :)

https://github.com/typelevel/cats-effect/blob/ab2a21e680b65c652abd3b5669b985c580cf262d/tests/jvm/src/test/scala/cats/effect/IOAppSpec.scala#L209-L220

**Comment by djspiewak** [comment]
Ooooooh. Duh
