### ISSUE TITLE
Application locks up and fiber dumps don't work anymore

### ISSUE THREAD

**Issue by msiegenthaler** [typelevel/cats-effect#3073]
My application completely locks up after some time of running fine. Symtopms:
* Nothing gets processed anymore
* Fiber dumps (kill -USR1 <pid>) give an error (see below)
* Thread dump shows no io-compute threads anymore, only the io-scheduler is still there. Also no io-compute-blocker
* Nothing shown on the application log - I have a Resource around everything that logs on termination

The application is a http4s webserver that makes some calls to a legacy library (keycloak-admin) using IO.interruptibleMany. The results are wrapped in streams (actually I do a paged load using streams with fs2.Stream.unfoldChunkEval). Running cats-effect 3.3.13 and fs2 3.2.9

Error from the fiber dump
```
Exception in thread "SIGUSR1 handler" java.lang.NullPointerException: Cannot invoke "cats.effect.unsafe.WeakBag.toSet()" because "this.fiberBag" is null
	at cats.effect.unsafe.WorkerThread.suspendedSnapshot(WorkerThread.scala:219)
	at cats.effect.unsafe.WorkStealingThreadPool.liveFibers(WorkStealingThreadPool.scala:491)
	at cats.effect.unsafe.FiberMonitor.$anonfun$liveFiberSnapshot$2(FiberMonitor.scala:92)
	at cats.effect.unsafe.FiberMonitor.$anonfun$liveFiberSnapshot$2$adapted(FiberMonitor.scala:91)
	at scala.Option.fold(Option.scala:263)
	at cats.effect.unsafe.FiberMonitor.liveFiberSnapshot(FiberMonitor.scala:91)
	at cats.effect.IOApp.$anonfun$main$8(IOApp.scala:260)
	at cats.effect.Signal.lambda$invocationHandlerFromConsumer$0(Signal.java:105)
	at com.sun.proxy.$Proxy3.handle(Unknown Source)
	at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:220)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by djspiewak** [comment]
I think I know what might be causing this.

So `interruptibleMany` spams interruption in a loop, specifically to circumvent scenarios where someone is catching and swallowing `InterruptibleException`. Unfortunately, exactly such a situation arises in the implementation of `interruptible` itself. We catch and swallow the exception, then shut off the interruption loop in the ensuing `finally` block. However, the loop could iterate a second time during this window and we don't do anything about it, meaning that the thread could have been interrupted *again* during the `finally`.

This wasn't really a problem in the past because all of this was being done on the blocking pool, but with the changes to the blocking semantics (pulling them into the compute pool), it now results in interruption happening on a `WorkerThread`, which I think is why the rest of the compute workers are being murdered. The problem is that the WSTP *correctly* handles thread interruption (most thread pools, including the JDK cached executor we used to use for blocking tasks), do not. This in turn means that the pool just dies because of a self-generated interruption.

The solution, I think, is that we need to clear the interruption flag *after* we're 100% certain that the interrupt loop has stopped. This can probably be done with a JDK `CountDownLatch`. As a workaround, `interruptible` and `blocking` should not exhibit this issue, though obviously if you *need* `interruptibleMany` then you're out of luck. Will work on a fix.

**Comment by msiegenthaler** [comment]
can confirm `blocking` and `interruptible` do not have the issue

**Comment by msiegenthaler** [comment]
https://github.com/msiegenthaler/cats-effect-3073-isolation does trigger it
