### ISSUE TITLE
AbstractMethodError exception in `IOApp` in 3.4.0-RC2 

### ISSUE THREAD

**Issue by iRevive** [typelevel/cats-effect#3203]
It seems that any class that extends IOApp from 3.3.x has this issue.

CE: **3.4.0-RC2** 
Scala: **2.13.8**, **3.2.0**

The snippet:
```scala
//> using scala "3.2.0"
//> using lib "org.typelevel::cats-effect::3.4.0-RC2"
//> using lib "com.monovore::decline-effect:2.3.1"

import cats.effect.*
import com.monovore.decline.Opts
import com.monovore.decline.effect.CommandIOApp

object Main extends CommandIOApp(name = "test", header = "header", version = "0.0.1") {
  def main: Opts[IO[ExitCode]] = 
    Opts.help.map(_ => IO.pure(ExitCode.Success))
}
```

Execution:
```shell
$ scala-cli run main.scala
Compiling project (Scala 3.2.0, JVM)
Compiled project (Scala 3.2.0, JVM)
Exception in thread "main" java.lang.AbstractMethodError: Receiver class Main$ does not define or inherit an implementation of the resolved method 'abstract void cats$effect$IOApp$_setter_$cats$effect$IOApp$$queue_$eq(java.util.concurrent.ArrayBlockingQueue)' of interface cats.effect.IOApp.
	at cats.effect.IOApp.$init$(IOApp.scala:190)
	at com.monovore.decline.effect.CommandIOApp.<init>(CommandIOApp.scala:12)
	at Main$.<init>(main.scala:9)
	at Main$.<clinit>(main.scala:9)
	at Main.main(main.scala)
```

**Comment by armanbilge** [comment]
Thanks for the report. Looks like we broke bincompat on Scala 3.

**Comment by armanbilge** [comment]
Looks like someone was very naughty 😛 
https://github.com/typelevel/cats-effect/blob/f847eb82c68bbc33e98ac13246943d99fb344f4d/build.sbt#L554-L558

**Comment by djspiewak** [comment]
🥺👉👈
