### ISSUE TITLE
Failed to register Cats Effect CPU starvation MBean

### ISSUE THREAD

**Issue by etspaceman** [typelevel/cats-effect#3268]
Some of our projects seem to be running into a non-deterministic error with Cats Effect 3.4.1:

```
[info]   [WARNING] Failed to register Cats Effect CPU starvation MBean, proceeding with
[info]   no-operation versions. You will not see MBean metrics for CPU starvation.
[info]   Exception follows: 
[info]    javax.management.NotCompliantMBeanException: MBean class cats.effect.metrics.CpuStarvation does not implement DynamicMBean, and neither follows the Standard MBean conventions (javax.management.NotCompliantMBeanException: Class cats.effect.metrics.CpuStarvation is not a JMX compliant Standard MBean) nor the MXBean conventions (javax.management.NotCompliantMBeanException: cats.effect.metrics.CpuStarvation: Class cats.effect.metrics.CpuStarvation is not a JMX compliant MXBean)
[info]   	at com.sun.jmx.mbeanserver.Introspector.checkCompliance(Introspector.java:176)
[info]   	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:317)
[info]   	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
```

**Comment by armanbilge** [comment]
Huh, I thought we fixed this in https://github.com/typelevel/cats-effect/pull/3243.

**Comment by erdeszt** [comment]
I've ran into the same issue and have a small example that can reproduce it:

```scala
package foo                                                                                                                                                                            
                                                                                                                                                                                          
import cats.effect.*                                                                                                                                                                     
import org.http4s.*                                                                                                                                                                      
import org.http4s.dsl.io.*                                                                                                                                                               
import org.http4s.netty.server.NettyServerBuilder                                                                                                                                        
                                                                                                                                                                                          
val routes = HttpRoutes.of[IO] { case GET -> Root =>                                                                                                                                     
  Ok("YO")                                                                                                                                                                               
}                                                                                                                                                                                        
                                                                                                                                                                                          
object Main extends IOApp:                                                                                                                                                               
  override def run(args: List[String]): IO[ExitCode] =                                                                                                                                   
    NettyServerBuilder[IO]                                                                                                                                                               
      .withHttpApp(routes.orNotFound)                                                                                                                                                    
      .bindHttp(8000, "0.0.0.0")                                                                                                                                                         
      .resource                                                                                                                                                                          
      .use(_ => IO.never)                                                                                                                                                                
      .as(ExitCode.Success)
```

This is on scala `3.2.0` with `cats-effect=3.4.6`, `http4s=1.0.0-M37` and `http4s-netty-server=0.6.0-M3`. The netty server doesn't support the newer http4s versions so I couldn't try with those. 

The warning produced is:
```
[WARNING] Failed to register Cats Effect CPU starvation MBean, proceeding with
no-operation versions. You will not see MBean metrics for CPU starvation.
Exception follows: 
 javax.management.InstanceAlreadyExistsException: cats.effect.metrics:type=CpuStarvation
        at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1865)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:960)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:895)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
        at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:523)
        at main$ @ foo.Main$.main(Main.scala:12)
        at main$ @ foo.Main$.main(Main.scala:12)
        at main$ @ foo.Main$.main(Main.scala:12)
        at main$ @ foo.Main$.main(Main.scala:12)
        at main$ @ foo.Main$.main(Main.scala:12)
```

Interestingly I don't get the warning when I remove the `host` parameter of the `bindHttp` call(changing it other values doesn't seem to fix it).

I hope this can help :)

Edit: It might be because of stuck background processes in sbt. If I kill the existing ones(that don't get killed by `ctrl+c` for some reason 😕 ) and then run the example app I don't get this error.

**Comment by armanbilge** [comment]
@erdeszt thanks for reporting! Are you using `fork := true` in your sbt?

**Comment by erdeszt** [comment]
@armanbilge no I was not using `fork := true` when I wrote that comment. Adding `fork := true` seems to fix the issue in my case.
