### ISSUE TITLE
Figure out how to reduce spurious blocking errors

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3436]
I absolutely love this:

```
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (WAITING)
  at java.base/jdk.internal.misc.Unsafe.park(Native Method)
  at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
  at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
  at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
  at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
  at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
  at java.base/jdk.internal.misc.InternalLock.lock(InternalLock.java:74)
  at java.base/java.io.PrintStream.writeln(PrintStream.java:823)
  at java.base/java.io.PrintStream.println(PrintStream.java:1167)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:438)
```

Stare at that for a second and think about what it really means. At least we know the detector is working fairly well!

**Comment by armanbilge** [comment]
> At least we know the detector is working fairly well!

💯

**Comment by mcenkar** [comment]
Hi,

I'll add here it happens quite a lot, even with such simple app as:

```scala
import cats.effect.{IO, IOApp}

object XD extends IOApp.Simple {
  override protected def blockedThreadDetectionEnabled: Boolean = true

  val run = IO(println("Hello, World!"))
}
```

I get anywhere between 0 and 4 warnings, for example:

```
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:651)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:768)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:778)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:778)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
```

You even get a warning about cats printing warning 😃 

```
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at java.base/java.lang.StackTraceElement.isHashedInJavaBase(StackTraceElement.java:522)
  at java.base/java.lang.StackTraceElement.computeFormat(StackTraceElement.java:488)
  at java.base/java.lang.StackTraceElement.of(StackTraceElement.java:585)
  at java.base/java.lang.Thread.asyncGetStackTrace(Thread.java:2470)
  at java.base/java.lang.Thread.getStackTrace(Thread.java:2447)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:771)
```

https://github.com/typelevel/cats-effect/blob/v3.6.1/core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala#L771

**Comment by djspiewak** [comment]
@mcenkar Worth noting that your app is in fact blocking on the compute thread! `IO(println(...))` blocks a compute thread, but `IO.println` does not. So the warnings in this case aren't actually spurious.

**Comment by mcenkar** [comment]
Interesting, there's quite a few examples like this here: https://github.com/search?q=repo%3Atypelevel%2Fcats-effect%20IO(println&type=code must have copied from one of those.

But I'm also able to reproduce this with following:

```scala
import cats.effect.{ExitCode, IO, IOApp}

object XD extends IOApp {
  override protected def blockedThreadDetectionEnabled: Boolean = true

  override def run(args: List[String]): IO[ExitCode] = IO.pure(ExitCode.Success)
}
```

and output:

```
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:651)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:753)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:651)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:753)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:651)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:753)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:651)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:753)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:651)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
  at cats.effect.unsafe.LocalQueue.lsb(LocalQueue.scala:773)
  at cats.effect.unsafe.LocalQueue.dequeue(LocalQueue.scala:415)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:842)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
```

**Comment by mcenkar** [comment]
Hi,

I believe I have found another example, more reproducible. It involves fs2 library, but fs2 is (usually) not printed in stacktraces so I assume bug is perhaps in cats. In case it looks like a bug with fs2 please let me know, I can open issue in there.

Example:

```scala
import cats.effect.{ExitCode, IO, IOApp}

object XD extends IOApp {
  override protected def blockedThreadDetectionEnabled: Boolean = true

  def run(args: List[String]): IO[ExitCode] =
    fs2.Stream
      .iterateEval(0)(IO.pure)
      .take(1024 * 1024 * 1024)
      .observe(p => p.drain)
      .compile
      .drain
      .map(_ => ExitCode.Success)
}
```

Basically generates 1 GB of 0s, and discards them. If you run usually it prints couple warnings at startup (as in example above) and after a while starts repeating more warnings. If you remove line `observe(p => p.drain)` only the startup warnings remain.

Warnings I see:

```
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at java.base/sun.nio.ch.KQueueSelectorImpl.clearInterrupt(KQueueSelectorImpl.java:310)
  at java.base/sun.nio.ch.KQueueSelectorImpl.processEvents(KQueueSelectorImpl.java:244)
  at java.base/sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:145)
  at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
  at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:147)
  at cats.effect.unsafe.SelectorSystem.poll(SelectorSystem.scala:48)
  at cats.effect.unsafe.SelectorSystem.poll(SelectorSystem.scala:28)
  at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:636)
  at cats.effect.unsafe.WorkerThread.park$1(WorkerThread.scala:587)
  at cats.effect.unsafe.WorkerThread.lookForWork$1(WorkerThread.scala:471)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:858)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at java.base/java.lang.ref.Reference.clear0(Native Method)
  at java.base/java.lang.ref.Reference.enqueue(Reference.java:514)
  at cats.effect.unsafe.WeakBag$Entry.deregister(WeakBag.scala:112)
  at cats.effect.IOFiber.loop$1(IOFiber.scala:670)
  at cats.effect.IOFiber.stateLoop$1(IOFiber.scala:746)
  at cats.effect.IOFiber.$anonfun$runLoop$1(IOFiber.scala:752)
  at cats.effect.IOFiber.$anonfun$runLoop$1$adapted(IOFiber.scala:642)
  at cats.effect.IOFiber.$anonfun$runLoop$7(IOFiber.scala:933)
  at cats.effect.IOFiber.$anonfun$runLoop$7$adapted(IOFiber.scala:933)
  at cats.effect.CallbackStack.apply(CallbackStack.scala:67)
  at cats.effect.IOFiber.done(IOFiber.scala:1097)
  at cats.effect.IOFiber.runTerminusSuccessK(IOFiber.scala:1491)
  at cats.effect.IOFiber.succeeded(IOFiber.scala:1244)
  at cats.effect.IOFiber.runLoop(IOFiber.scala:463)
  at cats.effect.IOFiber.execR(IOFiber.scala:1397)
  at cats.effect.IOFiber.run(IOFiber.scala:122)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:851)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at cats.effect.IOFiber.runLoop(IOFiber.scala:460)
  at cats.effect.IOFiber.execR(IOFiber.scala:1397)
  at cats.effect.IOFiber.run(IOFiber.scala:122)
  at cats.effect.unsafe.WorkerThread.lookForWork$1(WorkerThread.scala:443)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:858)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)
  at cats.effect.IOFiber.execR(IOFiber.scala:1397)
  at cats.effect.IOFiber.run(IOFiber.scala:122)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:851)
This is very likely to be due to suspending a blocking call in IO via
`IO.delay` or `IO.apply`. If this is the case then you should use
`IO.blocking` or `IO.interruptible` instead.
```

Please let me know if you think it's fs2 problem.
