### ISSUE TITLE
`ArrayIndexOutOfBoundsException` in `ByteStack`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3907]
Look I don't even know…

```
java.lang.ArrayIndexOutOfBoundsException: Index -268435455 out of bounds for length 402653184
  | => tat cats.effect.ByteStack$.push(ByteStack.scala:59)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:560)
	at cats.effect.IOFiber.autoCedeR(IOFiber.scala:1439)
	at cats.effect.IOFiber.run(IOFiber.scala:119)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:743)
```

See `DispatcherSpec` on the `aioobe-reproduction` tag at https://github.com/djspiewak/cats-effect

**Comment by durban** [comment]
I can't reproduce this (I get `OutOfMemoryError`s), but that exception more or less seems like what should happen if the size (`stack(0)`) overflowed from `Int.MaxValue` to `Int.MinValue`.

If in `push` the `val c` is `Int.MinValue`, then `val s = (c >> 3) + 1` will be -268435455 (the same as in the exception), which is used as an index in line 59.

**Comment by armanbilge** [comment]
Unless we want to add our own bounds check that gives a more helpful error message, can we close this?

**Comment by durban** [comment]
We could detect the overflow earlier, by using `Math.addExact`.
