### ISSUE TITLE
Potential binary incompatibility in 1.1.0

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#436]
I just got this by calling `transactor.configure` on a Doobie (0.6.0) transactor, after upgrading to cats-effect 1.1.0 in my app:

```
java.lang.NoSuchMethodError: cats.FlatMap.productR$(Lcats/FlatMap;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at cats.effect.IOLowPriorityInstances$IOEffect.productR(IO.scala:745)
	at cats.Apply.$times$greater(Apply.scala:120)
	at cats.Apply.$times$greater$(Apply.scala:11)
	at cats.effect.IOLowPriorityInstances$IOEffect.$times$greater(IO.scala:745)
	at cats.Apply$Ops.$times$greater(Apply.scala:11)
	at cats.Apply$Ops.$times$greater$(Apply.scala:11)
	at cats.syntax.ApplySyntax$$anon$1.$times$greater(apply.scala:6)
	at foo.bar.Database$.$anonfun$transactor$5(Database.scala:30)
	at doobie.util.transactor$Transactor.configure(transactor.scala:140)
	at foo.bar.Database$.$anonfun$transactor$4(Database.scala:28)
	at cats.effect.Resource.$anonfun$use$1(Resource.scala:120)
	at cats.effect.internals.IOBracket$BracketStart.liftedTree1$1(IOBracket.scala:79)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:79)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:44)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:337)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by mpilquist** [comment]
Can you check the version of cats-core you have in that project? I'm guessing it is older than 1.5.0.

**Comment by kubukoz** [comment]
Note: I was wondering if it's actualy cats-effect or cats 1.5.0, but I upgraded cats-core from 1.4.0 to 1.5.0 (leaving cats-effect at 1.0.0) and didn't have this issue.

**Comment by kubukoz** [comment]
OK, turns out that if I have a dependency on cats-core 1.4.0 and cats-effect 1.1.0, sbt picks cats-core 1.4.0... @mpilquist looks like you were right :)
