### ISSUE TITLE
scaladoc JS error prevents expandable content from becoming visible

### ISSUE THREAD

**Issue by arosien** [typelevel/cats-effect#760]
The [published scaladoc/API docs](https://typelevel.org/cats-effect/api/index.html), and all sub-pages, report an error in the JavaScript console, and as a result, no "expandable" field/method docs can actually be expanded. For example, [`IOApp#contextShift`](https://typelevel.org/cats-effect/api/cats/effect/IOApp.html#contextShift:cats.effect.ContextShift[cats.effect.IO]) has [extra content](https://github.com/typelevel/cats-effect/blob/v2.0.0/core/shared/src/main/scala/cats/effect/IOApp.scala#L72).

JavaScript errors:

```
jquery.panzoom.min.js:9 Uncaught TypeError: Cannot set property 'pointerover' of undefined
    at String.<anonymous> (jquery.panzoom.min.js:9)
    at Function.each (jquery.min.js:2)
    at jquery.panzoom.min.js:9
    at jquery.panzoom.min.js:9
    at jquery.panzoom.min.js:9
(anonymous) @ jquery.panzoom.min.js:9
each @ jquery.min.js:2
(anonymous) @ jquery.panzoom.min.js:9
(anonymous) @ jquery.panzoom.min.js:9
(anonymous) @ jquery.panzoom.min.js:9
jquery.min.js:2 jQuery.Deferred exception: $(...).panzoom is not a function TypeError: $(...).panzoom is not a function
    at HTMLDocument.<anonymous> (https://typelevel.org/cats-effect/api/lib/template.js:7:51)
    at e (https://typelevel.org/cats-effect/api/lib/jquery.min.js:2:29453)
    at t (https://typelevel.org/cats-effect/api/lib/jquery.min.js:2:29755) undefined
k.Deferred.exceptionHook @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
B @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: $(...).panzoom is not a function
    at HTMLDocument.<anonymous> (template.js:7)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)
```

**Comment by arosien** [comment]
This appears to have been fixed from the recent release (2.1.0?).
